name: cross-repo-pr

on:
  pull_request:
    types: [opened, reopened]

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.AUTOMATION_PAT }}"
          gh config set git_protocol https -h github.com

      - name: Clone Source Repo
        env:
          TARGET_REPO: "javiersariol97/cross-repo-pr-2" 
        run: |
          git clone $TARGET_REPO
          cd cross-repo-pr-2

      - name: Create PR in Target Repo
        env:
          TARGET_REPO: "javiersariol97/cross-repo-pr-2" 
          SOURCE_BRANCH: "development"
          TARGET_BRANCH: "staging"
        run: |
          # Crea el PR
          gh pr create \
            --title "Auto-PR from ${{ github.repository }}" \
            --body "Sincronización automática desde ${{ github.event.pull_request.html_url }}" \
            --base $TARGET_BRANCH \
            --head $SOURCE_BRANCH

          # Obtén el número del PR creado
          PR_NUMBER=$(gh pr list --state open --base $TARGET_BRANCH --json number -q ".[0].number")

          # Aprueba y mergea el PR
          gh pr review $PR_NUMBER --approve
          gh pr merge $PR_NUMBER --merge --delete-branch