name: Cross-Repo PR

on:
  pull_request:
    branches:
      - staging

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI for cloning and creating PR
        run: |
          gh auth login --with-token <<< "${{ secrets.AUTOMATION_PAT }}"
          gh config set git_protocol https -h github.com

      - name: Clone Target Repo
        run: |
          git clone https://github.com/${{ secrets.TARGET_REPO }}.git target-repo

      - name: Create PR in Target Repo
        env:
          TARGET_REPO: ${{ secrets.TARGET_REPO }}
          SOURCE_BRANCH: "development"
          TARGET_BRANCH: "staging"
        run: |
          # Crea el PR
          cd target-repo
          gh pr create \
            --title "Auto-PR from ${{ github.repository }}" \
            --body "Sincronización automática desde ${{ github.event.pull_request.html_url }}" \
            --base $TARGET_BRANCH \
            --head $SOURCE_BRANCH

          # Obtén el número del PR creado
          PR_NUMBER=$(gh pr list --state open --base $TARGET_BRANCH --json number -q ".[0].number")
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Set up GitHub CLI for approve and merge
        run: |
          gh auth logout
          gh auth login --with-token <<< "${{ secrets.AUTOMATION_PAT_APROBE }}"
          gh config set git_protocol https -h github.com

      - name: Approve and merge PR in Target Repo
        run: |
          # Aprueba y mergea el PR
          PR_NUMBER=$(echo $PR_NUMBER | cut -d "=" -f 2)
          echo "PR_NUMBER=$PR_NUMBER"
          cd target-repo
          gh pr review $PR_NUMBER --approve
          gh pr merge $PR_NUMBER --merge
          