name: cross-repo-pr

on:
  pull_request:
    branches:
      - staging

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI for cloning and creating PR
        run: |
          gh auth login --with-token <<< "${{ secrets.AUTOMATION_PAT }}"
          gh config set git_protocol https -h github.com

      - name: Clone Source Repo
        env:
          TARGET_REPO: "https://github.com/javiersariol97/cross-repo-pr-2.git" 
        run: |
          git clone $TARGET_REPO
          cd cross-repo-pr-2

      - name: Create PR in Target Repo
        env:
          TARGET_REPO: "javiersariol97/cross-repo-pr-2" 
          SOURCE_BRANCH: "development"
          TARGET_BRANCH: "staging"
        run: |
          # Crea el PR
          cd cross-repo-pr-2
          gh pr create \
            --title "Auto-PR from ${{ github.repository }}" \
            --body "Sincronización automática desde ${{ github.event.pull_request.html_url }}" \
            --base $TARGET_BRANCH \
            --head $SOURCE_BRANCH
            
            # Obtén el número del PR creado
            PR_NUMBER=$(gh pr list --state open --base $TARGET_BRANCH --json number -q ".[0].number")
            echo "PR_NUMBER=$PR_NUMBER"

      - name: Set up GitHub CLI for aprobe and merge
        run: |
          gh auth login --with-token <<< "${{ secrets.AUTOMATION_PAT_APROBE }}"
          gh config set git_protocol https -h github.com

      - name: Aprobe and merge PR in Target Repo
        run: |
          # Aprueba y mergea el PR
          echo "PR_NUMBER=$PR_NUMBER"
          cd cross-repo-pr-2
          gh pr review $PR_NUMBER --approve
          gh pr merge $PR_NUMBER --merge --delete-branch